### ISSUE TITLE
Duplicate entries in devices.h

### ISSUE THREAD

**Issue by rjwalsh** [vdudouyt/minipro#8] opened 2014-05-18 17:49 UTC
While working on the OS X port, I noticed that the devices.h entry for the M27C4001 @DIP32 was duplicated in the devices.h file. I wrote a python script to parse the file and print out any duplicate entries. When I run it, I see 1554 duplicate entries. Some are in there twice and some three times.

I put the script here: https://gist.github.com/rjwalsh/d85b898fa27a54034a22

**Comment by DavidGriffith** [comment] 2018-03-13 15:42
Duplicate of #64

**Closed by DavidGriffith** 2018-03-13 15:42 UTC
